### ISSUE TITLE
Filter does not support in expression

### ISSUE THREAD

**Issue by kanusiewicz** [IharYakimush/comminity-data-odata-linq#31]
sample filter: Param in (0,100)

throws exception:

 "ExceptionType": "System.NotImplementedException",
  "StackTrace": "   w Microsoft.OData.UriParser.QueryNodeVisitor`1.Visit(InNode nodeIn)\r\n   w Microsoft.OData.UriParser.InNode.Accept[T](QueryNodeVisitor`1 visitor)\r\n   w Community.OData.Linq.OData.Query.ParameterAliasNodeTranslator.Visit(ConvertNode nodeIn)\r\n   w Microsoft.OData.UriParser.ConvertNode.Accept[T](QueryNodeVisitor`1 visitor)\r\n   w Community.OData.Linq.OData.Query.ParameterAliasNodeTranslator.Visit(BinaryOperatorNode nodeIn)\r\n   w Microsoft.OData.UriParser.BinaryOperatorNode.Accept[T](QueryNodeVisitor`1 visitor)\r\n   w Community.OData.Linq.OData.Query.ParameterAliasNodeTranslator.Visit(BinaryOperatorNode nodeIn)\r\n   w Microsoft.OData.UriParser.BinaryOperatorNode.Accept[T](QueryNodeVisitor`1 visitor)\r\n   w Community.OData.Linq.OData.Query.ParameterAliasNodeTranslator.Visit(BinaryOperatorNode nodeIn)\r\n   w Microsoft.OData.UriParser.BinaryOperatorNode.Accept[T](QueryNodeVisitor`1 visitor)\r\n   w Community.OData.Linq.ODataLinqExtensions.Filter[T](ODataQuery`1 query, String filterText, String entitySetName)\r\n   w AbcData.Services.News.DataModel.NewsODataService.GetNews(String filter) w

**Comment by IharYakimush** [comment]
"In" logical operator is part of OData 4.01 (http://docs.oasis-open.org/odata/odata/v4.01/csprd02/part2-url-conventions/odata-v4.01-csprd02-part2-url-conventions.html).

Current project support only OData 4.0. It should throw `ODataException` with message about "Syntax error".

It looks like you using `Microsoft.OData.Core` of latest version which already can work with "In", so you got another exception.

**Comment by rtellez91** [comment]
Hi, so is there any workaround for that? I suppose that we can only rewrite de query in a multiple ORs way. Do you plan to add it as a support?

**Comment by GuusDb** [comment]
same issue here, is there a workaround. really need to use the in operator.

**Comment by mosqic33** [comment]
This problem also occurred when I used the in operator. Is there any solution?

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.OData.UriParser.QueryNodeVisitor`1.Visit(InNode nodeIn)
   at Microsoft.OData.UriParser.InNode.Accept[T](QueryNodeVisitor`1 visitor)

**Comment by ArnaudB88** [comment]
@kanusiewicz @GuusDb @rtellez91 @mosqic33 
I created a new version of the Community.Odata.Linq repository: [OData2Linq](https://github.com/ArnaudB88/OData2Linq/tree/feature/odata-link810)

After a few days of work and some beta releases, the v1.0.0 release is available on [NuGet](https://www.nuget.org/packages/OData2Linq/). As you can read in the [release notes](https://github.com/ArnaudB88/OData2Linq/releases), it is based on the Microsoft.AspNetCore.OData v8.1.0 library and supports the 'in' keyword.
